- name: check disk size
  hosts: size

  tasks:

    - name: check disk size         
      shell: "if [[ $(df -h /tmp/ | awk {'print $4'} | grep G | sed -r 's/G//') -lt 1 ]];
           then
                 echo PROBLEM!!!!!!!;
                 exit 1;
           else
                 echo good;
           fi"
      sudo: yes

    - name: validate continue
      shell: echo hello
      sudo: yes

    - name: mount logs foler
       #shell: "if [[ $(cat /etc/exports | grep logs | wc -l) -lt 1 ]];
       shell: "if [[ $(showmount -e | grep logs | wc -l) -lt 1 ]]; 
           then
                 echo PROBLEM!!!!!!!;
                 exit 1;
           else
                 echo good;
           fi"
      sudo: yes
  
    - name: validate continue
      shell: echo hello
      sudo: yes
