- name: check disk size
  hosts: size

  tasks:

    - name: check disk size         
      shell: "folder=/tmp/
              float=`df -h $folder | awk {'print $4'} | grep G | sed -r 's/G//'`
              int=${float%.*}

              if [[ $int -lt 100 ]];
                then
                  echo PROBLEM!!!!!!!;
                  exit 1;
              else
                  echo good;
              fi"
      sudo: yes

    - name: validate continue
      shell: echo hello
      sudo: yes

    - name: mount logs foler
      #shell: "if [[ $(cat /etc/exports | grep logs | wc -l) -lt 1 ]];
      shell: "if [[ $(showmount -e | grep logs | wc -l) -lt 1 ]]; 
           then
                 echo PROBLEM!!!!!!!;
                 exit 1;
           else
                 echo good;
           fi"
      sudo: yes
  
    - name: validate continue
      shell: echo hello
      sudo: yes
