- name: check disk size
  hosts: size

  tasks:

    - name: check disk size         
      shell: "if [[ $(df -h /tmp/ | awk {'print $4'} | grep G | sed -r 's/G//') -lt 1 ]];
           then
                 echo PROBLEM!!!!!!!;
                 exit 1;
           else
                 echo good;
           fi"
      sudo: yes

    - name: validate continue
      shell: echo hello
      sudo: yes


