- name: add users to sudoers
  hosts: 192.168.56.114
#  connection: local

  tasks:

#    - name: add users to sudoers file
#      lineinfile: dest=/etc/sudoers line="rudayashankar ALL=(ALL)       ALL"
#      lineinfile: dest=/etc/sudoers line="ykandasamy ALL=(ALL)       ALL"
#      lineinfile: dest=/etc/sudoers line="rsingh ALL=(ALL)       ALL"
#      sudo: yes

     - name: echo
       shell: df -h >> disk.txt 2>&1 
       sudo: yes
       ignore_errors: yes
