- name: tomcat test deploy
  hosts: tomcat
#  connection: local
  vars:
#   url: https://tomcat.apache.org/tomcat-7.0-doc/appdev/sample/sample.war
   url: http://192.168.56.125:8081/nexus/content/repositories/dima/tomcat/tomcat-test/{{ Artefact_Name }}/tomcat-test-{{ Artefact_Name}}.tar.gz
   webapp_folder: /usr/share/tomcat/webapps
   tomcat_user: tomcat
   user: admin
   pass: admin123  

  tasks:

     - name: check tomcat version
       shell: echo `tomcat version | awk {'print $4'} | head -1`
       sudo: yes
       register: version

     - name: download test artefact
       get_url: url="{{ url }}" dest="{{ webapp_folder }}" owner="{{ tomcat_user }}" group="{{ tomcat_user }}" url_username="{{ user }}" url_password="{{ pass }}"
       sudo: yes
       #sudo_user: "{{ tomcat_user }}"
      
     - name: unarchive
       unarchive: src=tomcat-test-{{ Artefact_Name}}.tar.gz 
       sudo: yes
       


     
       

